### ISSUE TITLE
can't login mastodon

### ISSUE THREAD

**Issue by inajob** [wtsnjp/twoot.py#3]
I coudn't login mastodon for initial setup.

```
$ python3 twoot.py -s
Welcome to Twoot! Please answer a few questions.

#1 First, decide about your application.
Name (optional; empty for "twoot.py"):
Website (optional; empty for "https://github.com/wtsnjp/twoot.py"):

#2 Tell me about your Mastodon account.
Instance (e.g., https://mastodon.social): https://mstdn.jp
Login e-mail (never stored): MY-EMAIL-ADDRESS
Login password (never stored): MY-PASSWORD
$
```

This script isn't support mstdn.jp?

**Comment by wtsnjp** [comment]
As far as I remember, the server (mstdn.jp) has a unique access restriction. You had to modify Mastodon.py to change the HTTP(S) request header to use another User-Agent. It seems Mastodon.py just recently started supporting custom User-Agent specifically for this reason (https://github.com/halcy/Mastodon.py/pull/240). So, if you install the latest Mastodon.py, hopefully, the problem will be solved.

**Comment by inajob** [comment]
thx for your information.
I modified your script and works fine!

I'll PR this change
